=head1 NAME

Toadfarm::Manual::RunningToadfarm - Command line options

=head1 DESCRIPTION

This manual goes through the command line options for C<toadfarm>.

=head2 Basics

You can start the application by running:

  # Run the Toadfarm application with hypnotoad
  $ /path/to/your-script start

=head2 Actions

In addition to all the default L<commands|Mojolicious::Commands/COMMANDS>,
L<Toadfarm> adds some more:

=over 4
=
=item * L<Toadfarm::Command::start>

  $ /path/to/your-script start

Will only start your application if not running.

=item * L<Toadfarm::Command::stop>

  $ /path/to/your-script stop

Will stop your application. Note that this command also
waits for the application to stop, which might take
L<several seconds|Mojo::Server::Hypnotoad/graceful_timeout>.

=item * L<Toadfarm::Command::reload>

  $ /path/to/your-script reload

Will either start the application or make it
L<hot deploy|Mojo::Server::Hypnotoad/USR2>.

=back

=head2 Init-V

Look at L<https://github.com/jhthorsen/toadfarm/tree/master/etc> for example
resources which show how to start L<Toadfarm> on ubuntu.

=head2 Crontab

  * * * * * /usr/local/bin/toadfarm -a My::App --start 1>/tmp/toadfarm.cron.log 2>&1

=head2 Other ways

It is possible to start the server using the standard L<Mojolicious> tools
as well:

  $ /path/to/your-script daemon --listen http://*:5000
  $ morbo /path/to/your-script
  $ hypnotoad /path/to/your-script

=head1 AUTHOR

Jan Henning Thorsen - C<jhthorsen@cpan.org>

=cut
