#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

@ARGV = grep { +(-r $_ ? ($ENV{MOJO_CONFIG} = $_, 0) : 1) } @ARGV;

if(@ARGV == 0 and !$ENV{MOJO_APP_LOADER}) {
    exec $ENV{MOJO_CONFIG} ? (hypnotoad => $0) : (perldoc => 'Toadfarm');
}

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Toadfarm');
