#!/bin/sh
cpanm --sudo -n Toadfarm
mkdir /var/run/toadfarm
chown www.www /var/run/toadfarm
touch /var/log/toadfarm.log
chown www.www /var/log/toadfarm.log

mkdir /etc/toadfarm
vim /etc/toadfarm/toadfarm.conf

cp ./etc/iptables.rules /etc/iptables.rules
cp ./etc/init.d/www /etc/init.d/www

chmod +x /etc/init.d/www
update-rc.d www defaults
/etc/init.d/www start
